version: '3'
services:
  app:
    build:
      dockerfile: ./Dockerfile
    tty: true
    # 高速化の設定
    volumes:
      - ../:/opt/app:delegated
      - node_modules_volume:/opt/app/node_modules

volumes:
  node_modules_volume:
